services: 
  db:
    image: postgres:18.0
    container_name: gogolf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - gogolf_pgdata:/var/lib/postgresql
  
  api:
    image: ghcr.io/samw94/gogolf-api:v0.0.1
    container_name: gogolf-api
    restart: unless-stopped
    environment:
      INTERNAL_PORT: 8080
      DB_URL: ${DB_URL_DOCKER}
    ports: 
      - "8080:8080"

volumes:
  gogolf_pgdata:
